### ISSUE TITLE
(Hint) Sometimes AI guesses 2 locations instead of guessing players

### ISSUE THREAD

**Issue by BrawleyGithub** [Drew61854/TerminalGames#6]
(Issue 1 of 2)
![image](https://github.com/Drew61854/TerminalGames/assets/130003223/7c7a812a-91e5-4403-87d9-99c0e05cf9eb)

**Comment by Drew61854** [comment]
@BrawleyGithub Thank you for bringing this up, you know the script by now. It was hard for me to replicate the glitch, as I think it has to do with what cards the AI is given at the beginning of the game, and is luck-based because of that. That being said, I think I have patched it out, but I'm not entirely sure as I couldn't reliably replicate it for testing. If the bug reappears in the posted new update, let me know.
